#!/bin/sh

# Dev
[ ! -d "$HOME/dev" ] && mkdir "$HOME/dev"

# xmonad
#[ ! -d "$HOME/.xmonad/" ] && mkdir -p "$HOME/.xmonad"
#ln -sfT "$HOME/dev/TARDIS/dotfiles/xmonad/xmonad.hs" "$HOME/.xmonad/xmonad.hs"
#ln -sfT "$HOME/dev/TARDIS/dotfiles/xmonad/.xmobarrc" "$HOME/.xmonad/.xmobarrc"

# Where to save wallpapers
[ ! -d "$HOME/Pictures/Wallpapers/" ] && mkdir -p "$HOME/Pictures/Wallpapers"
cp "./wallpaper.jpg"                              "$HOME/Pictures/Wallpapers/"

# Xdefaults
ln -sfT "$HOME/dev/TARDIS/dotfiles/Xdefaults" "$HOME/.Xdefaults"

# Bash
ln -sfT "$HOME/dev/TARDIS/dotfiles/bash/bashrc"       "$HOME/.bashrc"
ln -sfT "$HOME/dev/TARDIS/dotfiles/bash/bash_profile" "$HOME/.bash_profile"

# Git
ln -sfT "$HOME/dev/TARDIS/dotfiles/git/gitconfig" "$HOME/.gitconfig"

# Haskell stack
curl -sSL https://get.haskellstack.org/ | sh
