#!/bin/bash

for i in *.org; do
    [ -f "$i" ] || break
    emacs --batch --eval "(require 'org)" --eval "(org-babel-tangle-file \"$i\")"
done

[ ! -d "$HOME/Pictures/Wallpapers/" ] && mkdir -p "$HOME/Pictures/Wallpapers"

cp "./wallpaper.jpg" "$HOME/Pictures/Wallpapers/"

[ ! -d "$HOME/.emacs.d/" ] && mkdir -p "$HOME/.emacs.d"

ln -sf "$HOME/dev/TARDIS/init.el" "$HOME/.emacs.d/init.el"
